# ---------- Baselines (unchanged) ----------
GraphSAGE:
  encoder: [7, 64, 64, 8]
  decoder: [8, 64, 64, 1]

  nb_hidden_layers: 3
  size_hidden_layers: 64
  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  max_neighbors: 64
  bn_bool: True
  subsampling: 32000
  r: 0.05

PointNet:
  encoder: [7, 64, 64, 8]
  decoder: [8, 64, 64, 1]

  base_nb: 8
  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  subsampling: 32000

MLP:
  encoder: [7, 64, 64, 8]
  decoder: [8, 64, 64, 1]

  nb_hidden_layers: 3
  size_hidden_layers: 64
  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  bn_bool: True
  subsampling: 32000

GUNet:
  encoder: [7, 64, 64, 8]
  decoder: [8, 64, 64, 1]

  layer: 'SAGE'
  pool: 'random'
  nb_scale: 5
  pool_ratio: [.5, .5, .5, .5]
  list_r: [.05, .2, .5, 1, 10]
  size_hidden_layers: 8
  batchnorm: True
  res: False

  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  max_neighbors: 64
  subsampling: 32000
  r: 0.05

# ---------- Global-fusion variants (merge at 64) ----------
GraphSAGEGlobal:
  encoder: [7, 64, 64, 8]     # same as baseline encoder
  decoder: [8, 64, 64, 1]     # same as baseline decoder

  nb_hidden_layers: 3
  size_hidden_layers: 64
  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  max_neighbors: 64
  bn_bool: True
  subsampling: 32000
  r: 0.05

  # global fusion config
  use_global_fusion: true
  global_in: 1024
  global_fuse: 8               # fuse at encoder output dim (not 64)

PointNetGlobal:
  encoder: [7, 64, 64, 8]     # same as baseline
  decoder: [8, 64, 64, 1]     # same as baseline

  base_nb: 8
  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  subsampling: 32000

  use_global_fusion: true
  global_in: 1024
  global_fuse: 8              # fuse at encoder output dim (== 8)


MLPGlobal:
  encoder: [7, 64, 64, 8]     # <-- not [7, 64]
  decoder: [8, 64, 64, 1]     # decoder[0] matches encoder last = 8
  nb_hidden_layers: 3
  size_hidden_layers: 64
  bn_bool: True
  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  subsampling: 32000
  use_global_fusion: true
  global_in: 1024
  global_fuse: 8
  
GUNetGlobal:
  encoder: [7, 64, 64, 8]    # SAME as baseline
  decoder: [8, 64, 64, 1]    # SAME as baseline

  layer: 'SAGE'
  pool: 'random'
  nb_scale: 5
  pool_ratio: [.5, .5, .5, .5]
  list_r: [.05, .2, .5, 1, 10]
  size_hidden_layers: 8
  batchnorm: True
  res: False

  batch_size: 1
  nb_epochs: 398
  lr: 0.001
  max_neighbors: 64
  subsampling: 32000
  r: 0.05

  use_global_fusion: true
  global_in: 1024
  global_fuse: 8             # FUSE AT 8 (encoder output)